Migrate to Vite
graasp/graasp-app-sticky-notes pull request #142
Opened 2023-08-03 13:14 UTC by swouf

Migrate to Vite for building the app. Upgrades some dependencies on the way.

Close #141

2023-08-04 14:39 UTC, spaenleh requested changes
Very nice ! ⭐ Just a few comments, and some typos here and there.

2023-08-04 14:39 UTC, spaenleh commented on .github/workflows/deploy-prod.yml
> +name: Deploy to staging environment
You have a typo here, it should be `production`
```suggestion
name: Deploy to production environment
```

2023-08-04 14:39 UTC, spaenleh commented on .github/workflows/deploy-stage.yml
> +    name: Deploy to dev
```suggestion
    name: Deploy to staging
```

2023-08-04 14:39 UTC, spaenleh commented on package.json
> +    "build": "NODE_OPTIONS=--max_old_space_size=16384 && yarn vite build",
You should not need that option. Try removing it, and checking your versions of sdk, immutable etc to see if they match.

2023-08-04 14:39 UTC, spaenleh commented on package.json
> +    "preview": "yarn vite preview",
I think you can omit the `yarn` for these commands, `vite build` should be enough for example.

2023-08-04 14:39 UTC, spaenleh commented on package.json
>      "codacy-coverage": "3.4.0",
I don't think we use this anymore.

2023-08-04 14:39 UTC, spaenleh commented on package.json
>      "npm-run-all": "4.1.5",
I think this could be removed also.

2023-08-07 15:14 UTC, swouf commented on .github/workflows/deploy-dev.yml
> +    environment: development
Okay, I didn't know about that actually. I'll keep it then and will add the secrets to the development env.

2023-08-07 15:45 UTC, spaenleh commented
For your tests, you might want to lower the typing speed, it looks like some keystrokes are not sent to the text editor.

2023-08-07 15:46 UTC, spaenleh approved these changes
Looks good, let me know if the tests pass ✅

2023-08-08 07:36 UTC, merged