Migration to MUI5
graasp/graasp-app-sticky-notes pull request #74
Opened 2022-10-21 17:09 UTC by swouf

Close #69

2022-10-24 09:48 UTC, spaenleh requested changes
🎍Looks good, a few comments, and i am not sure that you want to use `vw` as units for your fontSize, but we can discuss.

2022-10-24 09:48 UTC, spaenleh commented on src/components/modes/student/StudentView.js
> +export default withTranslation()(StudentView);
I think if you use `useTranslation` hook inside all your functional components and you don't have any class components you can remove this, as it is useful to pass the `t` and `i18n` instances as props to the component.

2022-10-24 09:48 UTC, spaenleh commented on src/components/modes/teacher/ImageUpload.js
> +  fontSize: '1vw',
I am not sure you want to set your fontSize depending on the `viewWidth` (`vw`)  of the viewport. See [this article](https://www.freecodecamp.org/news/css-unit-guide/) for some alternatives.

2022-10-24 09:48 UTC, spaenleh commented on src/components/modes/teacher/Settings.js
> +            <Divider sx={{ mt: 2, mb: 2 }} />
`mt: 2, mb: 2` can be abreviated to `my: 2` (setting the margin on the y-axis using the short-hand property name)

2022-10-24 09:48 UTC, spaenleh commented on src/components/modes/teacher/TeacherView.js
> +export default withTranslation()(TeacherView);
Same as before, if ou are using `useTranslation` hook this is useless

2022-10-27 09:08 UTC, swouf commented on src/components/main/CanvasToolbar.js
> +      </ToolButton>
Yes, I changed it.

2022-10-27 09:40 UTC, swouf commented on src/components/main/CanvasScaleControl.js
> +const MainContainer = styled('div')(() => ({
Yes, I will change that I think. It is however not something that I will do immediately.

2022-10-28 08:22 UTC, spaenleh approved these changes
✨📝 Looks good to me ! Looking forward to using this new version of the app !

2022-10-28 08:24 UTC, merged